// Generated by CoffeeScript 1.10.0
(function() {
  var emscript, hashRGB, hasher, ref, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.emscript = emscript = (ref = root.emscript) != null ? ref : Module();

  hasher = null;

  root.hashRGB = hashRGB = function(pixels) {
    var RGB, b64, i, j, ptr, ref1;
    RGB = new Uint8Array(pixels.length * 3.0 / 4.0);
    for (i = j = 0, ref1 = pixels.length / 4.0; 0 <= ref1 ? j < ref1 : j > ref1; i = 0 <= ref1 ? ++j : --j) {
      RGB[3 * i + 0] = pixels[4 * i + 0];
      RGB[3 * i + 1] = pixels[4 * i + 1];
      RGB[3 * i + 2] = pixels[4 * i + 2];
    }
    hasher = hasher != null ? hasher : emscript.cwrap('pixelsToHashCode', 'string', ['number', 'number']);
    ptr = emscript._malloc(RGB.length);
    emscript.writeArrayToMemory(RGB, ptr);
    b64 = hasher(ptr, RGB.length);
    emscript._free(ptr);
    return b64;
  };

}).call(this);
