// Generated by CoffeeScript 1.10.0
(function() {
  var killCookie;

  window.killCookie = killCookie = function() {
    return Cookies.set('machine_fingerprinting_userid', 1, {
      expires: new Date(2000, 1, 1)
    });
  };

  $(function() {
    var c, commands, i, len, parser, ref, requests, seq, url;
    url = document.URL;
    parser = document.createElement('a');
    parser.href = url;
    commands = parser.search;
    requests = {};
    if (commands) {
      ref = commands.slice(1).split('&');
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        seq = c.split('=');
        requests[seq[0]] = seq[1];
      }
    }
    window.requests = requests;
    if (requests.hasOwnProperty('killCookie') && requests['killCookie'] === 'true') {
      return killCookie();
    }
  });

}).call(this);
