CREATE TABLE features (
	IP VARCHAR(32) NOT NULL,
	fontlist TEXT,
	inc TEXT,
	gpu TEXT,
	timezone INT(11),
	resolution TEXT,
	plugins TEXT, 
	cookie TEXT, 
	localstorage TEXT, 
	gpuImgs TEXT, 
	adblock TEXT, 
	cpu_cores INT(11),
	canvas_test TEXT, 
	audio TEXT, 
	langsdetected TEXT, 
	agent TEXT, 
	accept TEXT, 
	encoding TEXT, 
	language TEXT, 
	fonts TEXT, 
	WebGL TEXT, 
	browser_fingerprint TEXT, 
	computer_fingerprint_1 TEXT,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);